version: '2'
networks:
  vhosts:
    external: 
      name: nginx_vhosts
services:
  main: &main
    build: .
    ports: ['1337:1337']
  runrunrun:
    <<: *main
    ports: []
    restart: always
    networks:
    - vhosts
